version: "3.1"
services:
    webserver:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: conquer-webserver
      working_dir: /app
      ports:
        - "8182:8182"