version: "3.1"
services:
  mysql:
    image: mysql:8.0
    container_name: conquer-mysql
    working_dir: /app
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=conquer
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=9096
    ports:
      - "9096:9096"

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conquer-webserver
    working_dir: /app
    ports:
      - "8182:8182"